/**
 * The canonical set of 75 seeded Blind 75 problem slugs.
 *
 * This lives here — runtime-neutral, zero database/Prisma/Node-only
 * dependencies — so both the database package's oracle/seed validation and
 * the C++ contract registry validation can compare against a single source
 * of truth without either package importing the other in a way that would
 * create a cycle (packages/database depends on packages/shared, never the
 * reverse).
 */
export const CANONICAL_75_SLUGS = [
  "add-and-search-word-data-structure-design",
  "alien-dictionary",
  "best-time-to-buy-and-sell-stock",
  "binary-search",
  "binary-tree-level-order-traversal",
  "binary-tree-maximum-path-sum",
  "climbing-stairs",
  "clone-graph",
  "coin-change",
  "combination-sum",
  "construct-binary-tree-from-preorder-and-inorder-traversal",
  "container-with-most-water",
  "contains-duplicate",
  "counting-bits",
  "course-schedule",
  "decode-ways",
  "encode-and-decode-strings",
  "find-minimum-in-rotated-sorted-array",
  "fizz-buzz",
  "graph-valid-tree",
  "group-anagrams",
  "house-robber",
  "house-robber-ii",
  "implement-trie-prefix-tree",
  "insert-interval",
  "invert-binary-tree",
  "jump-game",
  "kth-smallest-element-in-a-bst",
  "linked-list-cycle",
  "longest-common-subsequence",
  "longest-consecutive-sequence",
  "longest-increasing-subsequence",
  "longest-repeating-character-replacement",
  "longest-substring",
  "lowest-common-ancestor-of-a-binary-search-tree",
  "maximum-depth-of-binary-tree",
  "maximum-product-subarray",
  "maximum-subarray",
  "meeting-rooms",
  "meeting-rooms-ii",
  "merge-intervals",
  "merge-k-sorted-lists",
  "merge-two-sorted-lists",
  "minimum-window-substring",
  "missing-number",
  "non-overlapping-intervals",
  "number-of-1-bits",
  "number-of-connected-components-in-an-undirected-graph",
  "number-of-islands",
  "pacific-atlantic-water-flow",
  "palindromic-substrings",
  "product-of-array-except-self",
  "remove-nth-node-from-end-of-list",
  "reorder-list",
  "reverse-bits",
  "reverse-linked-list",
  "reverse-string",
  "rotate-image",
  "same-tree",
  "search-in-rotated-sorted-array",
  "serialize-and-deserialize-binary-tree",
  "set-matrix-zeroes",
  "spiral-matrix",
  "subtree-of-another-tree",
  "sum-of-two-integers",
  "three-sum",
  "top-k-frequent-elements",
  "two-sum",
  "unique-paths",
  "valid-anagram",
  "valid-palindrome",
  "valid-parentheses",
  "validate-binary-search-tree",
  "word-break",
  "word-search",
] as const;

export type CanonicalSlug = (typeof CANONICAL_75_SLUGS)[number];
